name: Go

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build
        run: |
          mkdir -p bin
          go build -v -o bin/ .

      - name: Test
        run: go test -v ./...

      - name: Bundle
        run: |
          mkdir -p bundle
          cp -r bin/* bundle/
          cp -r templates bundle/

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: bundle/
